#!/bin/bash

# Set workdir to repository root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "${REPO_ROOT}"

# Run workflow using local secrets file if it exists
SECRETS_FILE="act_setup/local.secrets"

if [ ! -f "$SECRETS_FILE" ]; then
    echo "Error: $SECRETS_FILE not found."
    echo "Please create it with required secrets: SERVICE_ACCOUNT_JSON, JIRA_AUTH_TOKEN, etc."
    exit 1
fi

echo "Running workflow with secrets from $SECRETS_FILE..."

# Clean up .config/service_account.json after run to avoid confusion (generated by the workflow)
trap 'rm -f .config/service_account.json' EXIT

# Run act
# We don't need to manually create .config/service_account.json here anymore; 
# the workflow step "Setup Service Account" does it using the SERVICE_ACCOUNT_JSON secret.
# We just pass the secrets file.

act --job update-sheet \
    --secret-file "$SECRETS_FILE" \
    --bind